### ISSUE TITLE
Crash on Android 10

### ISSUE THREAD

**Issue by MrIkso** [firebirdberlin/nightdream#184]
Hello, app crashes on Android 10. Log
```
Process: com.firebirdberlin.nightdream
PID: 9186
UID: 11324
Flags: 0x3088be44
Package: com.firebirdberlin.nightdream v269 (2.9.7)
Foreground: Yes
Build: Xiaomi/dipper/dipper:8.1.0/OPM1.171019.011/V9.5.5.0.OEAMIFA:user/release-keys

java.lang.IllegalStateException: Could not execute method for android:onClick
 at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(Unknown Source:34)
 at android.view.View.performClick(Unknown Source:17)
 at android.view.View.performClickInternal(Unknown Source:3)
 at android.view.View.access$3500(Unknown Source:0)
 at android.view.View$PerformClick.run(Unknown Source:8)
 at android.os.Handler.handleCallback(Unknown Source:2)
 at android.os.Handler.dispatchMessage(Unknown Source:4)
 at android.os.Looper.loop(Unknown Source:242)
 at android.app.ActivityThread.main(Unknown Source:98)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
 at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(Unknown Source:25)
 ... 11 more
Caused by: java.lang.NullPointerException
 at android.content.res.XmlBlock.nativeGetStyleAttribute(Native Method)
 at android.content.res.XmlBlock.access$1500(Unknown Source:0)
 at android.content.res.XmlBlock$Parser.getStyleAttribute(Unknown Source:2)
 at android.content.res.Resources$Theme.getExplicitStyle(Unknown Source:4)
 at android.view.View.retrieveExplicitStyle(Unknown Source:5)
 at android.view.View.<init>(Unknown Source:29)
 at android.view.ViewGroup.<init>(Unknown Source:0)
 at android.widget.RelativeLayout.<init>(Unknown Source:0)
 at android.widget.RelativeLayout.<init>(Unknown Source:1)
 at android.widget.RelativeLayout.<init>(Unknown Source:1)
 at com.firebirdberlin.nightdream.ui.WebRadioLayout.<init>(Unknown Source:0)
 at com.firebirdberlin.nightdream.ui.BottomPanelLayout.showWebRadioView(Unknown Source:23)
 at com.firebirdberlin.nightdream.ui.BottomPanelLayout.setup(Unknown Source:16)
 at com.firebirdberlin.nightdream.ui.BottomPanelLayout.setActivePanel(Unknown Source:2)
 at com.firebirdberlin.nightdream.NightDreamActivity.onRadioClick(Unknown Source:46)
 ... 13 more
```

**Comment by mastermichi** [comment]
We have done a lot of work to improve compatibility on Android 10.
Is the problem still active?
